### ISSUE TITLE
Error npm installing this on WSL bash on Win10

### ISSUE THREAD

**Issue by mjosborne1** [danurbanowicz/eleventy-netlify-boilerplate#21]
verbose stack Error: ENOENT: no such file or directory, rename '/c/Users/Osbor/Dropbox/www/ssg-11ty/eleventy-netlify-boilerplate/node_modules/lodash' -> '/c/Users/Osbor/Dropbox/www/ssg-11ty/eleventy-netlify-boilerplate/node_modules/.lodash.DELETE'

[npm.log](https://github.com/danurbanowicz/eleventy-netlify-boilerplate/files/3813959/npm.log)

node version is 10.16.3
Ubuntu version is 18.04 LTS

**Comment by danurbanowicz** [comment]
Hmm not sure.. have you tried removing the node_modules folder and running `npm install` again?

**Comment by danurbanowicz** [comment]
Closing this issue for now. Let me know if you're still having problems and I will re-open it.
