### ISSUE TITLE
support for images

### ISSUE THREAD

**Issue by Blockchainbrett** [danurbanowicz/eleventy-netlify-boilerplate#29]
hey Im trying to just add images to posts and the home page

i added the png to the /img folder and referencing them in the `home.md` and the `firstpost.md` with the following format

`![](/img/CryptoArtDigestLogo.png)`

is there anything else I need to do? they wont show up and im used to this working on another gatsbyJS site I use.

**Comment by danurbanowicz** [comment]
Hi, it looks like your file path is missing the `/static/` parent folder, which is where we output our static assets.

It should be:

`![](/static/img/CryptoArtDigestLogo.png)`

Hopefully that fixes it for you.

**Comment by danurbanowicz** [comment]
Closing this now, but please feel free to re-open if your issue is not resolved.
