### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by Paul-dH** [danurbanowicz/eleventy-netlify-boilerplate#3]
Hi,

When I cloned the repro there was a small typo at:
eleventy-netlify-boilerplate/admin/config.yml

Line 27 should be:
create: false (without the single quotes)

Thanks for the starter project, it works great!

**Comment by danurbanowicz** [comment]
Thanks Paul, well spotted! Now fixed with commit 41effb783f854bd87d054b6d3fed67c5e9ef45bc
