### ISSUE TITLE
Multiple authors ?

### ISSUE THREAD

**Issue by ImaCrea** [danurbanowicz/eleventy-netlify-boilerplate#34]
Hi there;
thank you very much for your great boilerplate. I'm super new with 11ty+netlify CMS (coming from Jekyll+prose) and it looks amazing.

I see there's one author displayed on every post I create which is you. I understood it comes from metadata.json data file but how does it work if I have a multi-authors blog? Let's say there a few people with their own netlify identity who connect to the CMS and write their own post: is it possible to have their name in author then and if yes, how?

Thanks a lot

**Comment by danurbanowicz** [comment]
Good question!

You could potentially do something like that but you'd need to somehow connect your Eleventy output with Netlify CMS and Netlify Identity; which would bit outside the scope of this simple repo, I feel.

There has been some talk over at Netlify CMS of doing something like this, perhaps it might help you: https://github.com/netlify/netlify-cms/issues/1483

For the time being though, I've added some support for multiple authors (using a folder collection), and managing them in Netlify CMS. It's basic but long overdue, so I thank you for reminding me to do this!

**Comment by ImaCrea** [comment]
Hi, thanks for your answer and adding support for multiple authors through collections. Thanks I'll see how I can update my fork with your latest commits :)
