### ISSUE TITLE
Auto-redirect doesn't work

### ISSUE THREAD

**Issue by PierW** [danurbanowicz/eleventy-netlify-boilerplate#37]
On production (netlify) there is a problem with the redirect after the login in admin area.
I tried to insert this in homepage... it's works fine but just on local:
`    <script>
      if (window.netlifyIdentity) {
          window.netlifyIdentity.on("init", user => {
          if (!user) {
              window.netlifyIdentity.on("login", () => {
              document.location.href = "/admin/";
              });
          }
          });
      }
	  </script>`

in production I still have to press the button: "Login with Netlify Identity"

**Comment by danurbanowicz** [comment]
Hi, this is indeed annoying and I think it may be related to an issue with gotrue-js not updating the user token on first load.

https://github.com/netlify/gotrue-js/issues/71

Add to that the various [UX concerns](https://github.com/netlify/netlify-identity-widget/issues?q=is%3Aissue+is%3Aopen+login+) with the Netlify Identity Widget, I'm not sure what we can do to fix it right now.
