### ISSUE TITLE
Images and text are not fully responsive/cut off on mobile

### ISSUE THREAD

**Issue by zachco** [danurbanowicz/eleventy-netlify-boilerplate#38]
Not sure if its a CSS issue or you'd need to use something like the Eleventy image responsiver [plugin](https://www.npmjs.com/package/eleventy-plugin-images-responsiver), but it would be nice for the text and images to be fully responsive and not cut off on mobile and browser resize.

Taken on my computer (not zoomed):
<img width="652" alt="Screen Shot 2020-06-23 at 1 21 50 PM" src="https://user-images.githubusercontent.com/38992901/85457134-89ae4000-b554-11ea-9ec3-f9af89822a5b.png">

Taken on my phone (not zoomed):
<img width="652" src="https://user-images.githubusercontent.com/38992901/85457374-dabe3400-b554-11ea-8f8a-63c2ac22b959.jpg">

Thank you!

**Comment by danurbanowicz** [comment]
Basic responsive image support was missing from the stylesheet for some reason :astonished: and has now been added with commit https://github.com/danurbanowicz/eleventy-netlify-boilerplate/commit/b1083a2e8dad0df36a892c6970dadd5eb1de3e3d

These two lines of CSS will ensure that images do not grow outside of their parent container.

```
img {
  max-width: 100%;
  height: auto;
}
```

Anything more snazzy than that is probably outside the scope of this template, although the plugins you mentioned look quite interesting.
