### ISSUE TITLE
date time issues

### ISSUE THREAD

**Issue by bridgestew** [danurbanowicz/eleventy-netlify-boilerplate#5]
I'm aware of the Eleventy pitfall with datetime. Did you find a way to get around it using Netlify CMS's datetime widget? I haven't resolved it and would love any pointers if you have them.

Thanks!

**Comment by danurbanowicz** [comment]
Can you provide a bit more info on the problem you're having exactly? Are you working with different timezones? I haven't had any problems when explicitly setting the post date to a valid UTC string (which is what the Netlify CMS datetime widget outputs). Thanks!

**Comment by bridgestew** [comment]
Yes, I'm working with Eastern Time, mainly. If I understand your comment above, it might be easier to shift my desire to post based on my timezone. :)

**Comment by danurbanowicz** [comment]
Hmm I guess that your post's dates are off because Netlify is not aware of your local time zone. You can fix this by setting your local time zone explicitly in your app's `netlify.toml` file with a build environment variable like so:-

```
[build.environment]
  TZ = "America/New_York"
```

**Comment by danurbanowicz** [comment]
I'm going to close this issue now but feel free to re-open it if you haven't managed to find a solution.
