### ISSUE TITLE
CMS access for private forked repo

### ISSUE THREAD

**Issue by manikantag** [danurbanowicz/eleventy-netlify-boilerplate#61]
**Describe the bug**
Not able to use Netlify CMS when forked as private repo.

**To Reproduce**
1. Fork repo as Private and access `<siteurl>/admin`
2. Not able to login using Netlify auth

**Expected behavior**
Should be able to access `/admin` for private repo too

**Desktop (please complete the following information):**
 - OS: Not OS specific, but tested in Ubuntu and Win10
 - Browser: all browsers
 - Version: 9 Dec 2020 

**Smartphone (please complete the following information):**
 - Device: Not specific
 - OS: Not specific
 - Browser: Chrome
 - Version: 9 Dec 2020 

**Additional context**
Posted same question in Netlify Community: https://community.netlify.com/t/allowing-git-gateway-for-single-private-repo/28933

**Comment by danurbanowicz** [comment]
Hi! Have you looked at the Gotchas section in the readme?

https://github.com/danurbanowicz/eleventy-netlify-boilerplate#gotchas

You might need to regenerate your Github access token after forking to a private repo.

**Comment by manikantag** [comment]
Yeah, but then the Netlify Identity is asking for access on all private repos. Is there any way/workflow so that only the forked private repo access is sufficient?

This is issue is rather a question, not an issue with the project.

**Comment by manikantag** [comment]
For now I created new Github account with just one private repo and gave whatever permissions Netlify is asking, and everything is working as expected. But I didn't liked this, and waiting for any improvements from Netlify in future.
