### ISSUE TITLE
Use minifyCSS and minifyJS options in html-minifier instead?

### ISSUE THREAD

**Issue by anghelos** [danurbanowicz/eleventy-netlify-boilerplate#65]
I noticed that html-minifier includes both clean-css and UglifyJS, which can be turned on with an option.
Wouldn't doing all of this in a single pass improve build time?

**Comment by danurbanowicz** [comment]
This is an interesting question. Do you have any test results comparing both methods that you can share e.g. build stats from 11ty `DEBUG`? It’d be interesting to see if there is much of a difference.

**Comment by anghelos** [comment]
I have to admit I'm a little new to all this. I'm building a rather small site that I'm guessing won't give useful results. I'll still give it a go when I have the time.

**Comment by danurbanowicz** [comment]
For a small site with only a handful of pages, any difference in total build time is likely to be in milliseconds. But if you had thousands of pages, it could add up and be worth exploring!
