### ISSUE TITLE
Using TailwindCSS

### ISSUE THREAD

**Issue by kylesloper** [danurbanowicz/eleventy-netlify-boilerplate#66]
Hey man, I've been looking into Tailwind x Eleventy projects all day and so far they have all been based off of skeleton templates of Eleventy. Do you have any idea how I could use Tailwind with this template: set up, required plugin etc.

Thanks for your help.

**Comment by danurbanowicz** [comment]
I see you've already found the 11ty Tailwind CSS plugin over at: https://github.com/dafiulh/eleventy-plugin-tailwindcss

It should do what you want. This is the plugin I was going to recommend for using Tailwind with this project.
