### ISSUE TITLE
v2 beta update

### ISSUE THREAD

**Issue by rdela** [danurbanowicz/eleventy-netlify-boilerplate#72]
Hello and thanks for all the work here. With the v2 beta being out I am wondering if there are plans to update this starter or an appetite for contributions in that vein yet.

https://www.11ty.dev/blog/eleventy-v2-beta/

Trying to decide whether to start here or with Eleventy Base Blog v8.

https://www.11ty.dev/blog/bbv8/

**Comment by theapplegates** [comment]
Thank you. That sounds exciting. Like rdela says everyone appreciates your hard work. Can't wait to see your enhancements.

**Comment by rdela** [comment]
The new features and enhancements you mentioned sound very welcome! Please let me know how I can help without getting in your way.

**Comment by danurbanowicz** [comment]
PR https://github.com/danurbanowicz/eleventy-netlify-boilerplate/pull/73#issue-1575765621 brings Eleventy version up to v2.0.0 and adds some other small changes.

I guess the elephant in the room currently is that [Netlify CMS is now effectively abandoned](https://answers.netlify.com/t/is-this-project-dead/70988) and that there is no obvious replacement. While it still works fine and has lots of forks, it is probably time to start thinking about an alternative.

Next task for this starter: [Eleventy Image](https://www.11ty.dev/docs/plugins/image/) support with native lazy loading.

Any other ideas or feature requests are welcome!

**Comment by danurbanowicz** [comment]
Moving new feature discussion and requests into this pinned issue: #74
