### ISSUE TITLE
Markdown widget not wrapping output with HTML

### ISSUE THREAD

**Issue by danpantinople** [danurbanowicz/eleventy-netlify-boilerplate#8]
Hi, I'm using your boilerplate for my project and is using many markdown widgets on a single collection. 

In my config.yml, i have this as one of my fields:
`- { label: "Description", name: "featureDescription", widget: "markdown" }
`
I have a multi-paragraph content which then saves to my file.md's frontmatter like this:
![image](https://user-images.githubusercontent.com/40259701/52406215-24e17980-2b08-11e9-911b-e8e9c487fcc7.png)

and using `{{ projectInformation.projectDescription }}` it gets displayed in my site like this: 
![image](https://user-images.githubusercontent.com/40259701/52406256-3aef3a00-2b08-11e9-8ae4-a96517e4162c.png)

Also saw this in the netlifycms doc:
Please note: The markdown widget outputs a raw markdown string. Your static site generator may or may not render the markdown to HTML automatically. Consult with your static site generator's documentation for more information about rendering markdown.

Can you help me out? Thanks!

**Comment by danurbanowicz** [comment]
I think you're going to need to use a markdown filter like [markdown-it](https://github.com/markdown-it/markdown-it) to do what you're asking.

[Here is an example](https://github.com/alexcarpenter/alexcarpenter.me/blob/master/config/eleventy.config.js) of it being configured with Eleventy, it may help.

**Comment by danpantinople** [comment]
@danurbanowicz thanks for the reply but the thing is its already in eleventy.js
![image](https://user-images.githubusercontent.com/40259701/52422490-18254b80-2b31-11e9-9b81-9ab49e31e2d0.png)

**Comment by danpantinople** [comment]
Actually that helped! thanks @danurbanowicz

**Comment by danurbanowicz** [comment]
I'm closing this issue now but feel free to add a comment if you haven't managed to find a solution and I will re-open it for you :+1:
