### ISSUE TITLE
error in building after changing the image at homepage (maybe template syntax error)

### ISSUE THREAD

**Issue by pragyanone** [danurbanowicz/eleventy-netlify-boilerplate#80]
**Describe the bug**
After I change the homepage image, the site is not longer building

**To Reproduce**
1. change homepage image by uploading new image from the cms.
2. website no longer builds

**Expected behavior**
website should build and deploy with new uploaded image.

**Screenshots**
![image](https://github.com/danurbanowicz/eleventy-netlify-boilerplate/assets/59058629/ec5186a2-11a9-4894-b1c1-ffd5b45ab72c)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser edge
 - Version 120.0.2210.91 (Official build) (64-bit)

**Comment by danurbanowicz** [comment]
Hi @pragyanone, This boilerplate project doesn't include Eleventy Image out of the box and I can't see your code, but it looks like the image path in your template file is incorrect so Eleventy Image is unable to find it.

Check that the file path in your image shortcode matches the uploaded image file path and you should be good to go.

I'm closing this issue as it's outside of the project scope but feel free to re-open if you need to.
